export const EN = {
    menuTitle: "Let's Go!",
    menuSubtitle: "Adventures in Yopal, Casanare.",
    btn1p: "1 Player",
    btn1pSub: "(El Llanero)",
    btn2p: "2 Players",
    btn2pSub: "(Couple Local)",
    btnOnline: "Online Duel",
    btnOnlineSub: "(Remote)",
    swapBtn: "⇄ Swap P2 Controls",
    settingsBtn: "⚙️ Settings",
    controlsInfo: "1 Player Mode uses Arrows OR WASD",
    mobileSwipe: "Swipe to control! 👆",
    mobileJoy: "Use the joystick! 🕹️",
    settingsTitle: "Settings",
    joyLabel: "Enable Virtual Joystick",
    bombLabel: "Enable 'Fireball'",
    musicLabel: "Background Music",
    musicStyleLabel: "Music Style:",
    retroLabel: "Nokia 1100 Mode (Retro)",
    narratorAudioLabel: "Narrator Voice (AI)",
    narratorTextLabel: "Text Messages",
    diffLabel: "Difficulty:",
    optEasy: "Easy (Slow)",
    optMedium: "Medium",
    optHard: "Hard (Fast)",
    mobSetHint: "Joystick Setting applies only to Mobile.",
    closeBtn: "Close",
    gameOver: "GAME OVER",
    tie: "Double Crash! It's a Tie!",
    winP1: "El Llanero (Husband) Wins!",
    winP2: "La Llanera (Wife) Wins!",
    win1P: "Score: {score}! Great Job!",
    p1Label: "Husband (P1)",
    p2Label: "Wife (P2)",
    langLabel: "Language / Idioma",
    loadingAi: "Generating plains landscape...",
    narratorLabel: "🎙️ Local Narrator:",
    duelTitle: "🔥 Prairie Duel 🔥",
    ties: "Ties",
    gastronomyBtn: "🍽️ Gastronomy Gallery",
    saveScoreBtn: "Save",
    enterInitials: "New High Score! Initials:",
    musicJoropo: "Joropo (Classic)",
    musicCountry: "Country (USA)",
    musicMix: "North-South Fusion",
    musicRetro: "Retro (Beeps)",
    lobbyTitle: "Multiplayer Lobby",
    hostBtn: "Create Room",
    joinBtn: "Join Room",
    roomCode: "Room Code:",
    enterCode: "Enter Code:",
    waiting: "Waiting for opponent...",
    copyBtn: "Copy",
    connectBtn: "Connect",
    cancelBtn: "Cancel",
    mpDesc: "Play with a friend on another computer.",
    // Lobby Translations
    lobbyReady: "Ready",
    lobbySyncing: "Syncing...",
    lobbyLoading: "Loading",
    lobbyHost: "Host",
    lobbyGuest: "Guest",
    lobbyStart: "START GAME",
    lobbyWaitAssets: "Waiting for assets to load...",
    lobbyAllReady: "All players ready!",
    lobbyYouReady: "You are Ready!",
    lobbyLoadingAssets: "Loading assets...",
    lobbyWaitHost: "Waiting for Host...",
    rematchBtn: "Rematch",
    exitRoomBtn: "Exit Room",
    waitHostRestart: "Waiting for Host..."
};