export const ES = {
    menuTitle: "¡Vamonos!",
    menuSubtitle: "Aventuras en Yopal, Casanare.",
    btn1p: "1 Jugador",
    btn1pSub: "(El Llanero)",
    btn2p: "2 Jugadores",
    btn2pSub: "(Pareja Local)",
    btnOnline: "Duelo Online",
    btnOnlineSub: "(Remoto)",
    swapBtn: "⇄ Cambiar Controles P2",
    settingsBtn: "⚙️ Configuración",
    controlsInfo: "Modo 1 Jugador usa Flechas O WASD",
    mobileSwipe: "¡Desliza para controlar! 👆",
    mobileJoy: "¡Usa la palanca! 🕹️",
    settingsTitle: "Configuración",
    joyLabel: "Activar Joystick Virtual",
    bombLabel: "Activar 'Bola de Fuego'",
    musicLabel: "Música de Fondo",
    musicStyleLabel: "Estilo Musical:",
    retroLabel: "Modo Nokia 1100 (Retro)",
    narratorAudioLabel: "Voz del Narrador (IA)",
    narratorTextLabel: "Mensajes de Texto",
    mythicalBossesLabel: "Activar Jefes Míticos (El Silbón, etc.)",
    diffLabel: "Dificultad:",
    optEasy: "Fácil (Lento)",
    optMedium: "Medio",
    optHard: "Difícil (Rápido)",
    mobSetHint: "La opción Joystick solo aplica en móvil.",
    closeBtn: "Cerrar",
    gameOver: "JUEGO TERMINADO",
    tie: "¡Choque Doble! ¡Empate!",
    winP1: "¡Ganó El Llanero (Esposo)!",
    winP2: "¡Ganó La Llanera (Esposa)!",
    win1P: "¡Puntaje: {score}! ¡Buen trabajo!",
    p1Label: "Esposo (P1)",
    p2Label: "Esposa (P2)",
    langLabel: "Idioma / Language",
    loadingAi: "Generando paisaje llanero...",
    narratorLabel: "🎙️ Narrador Criollo:",
    duelTitle: "🔥 Duelo Criollo 🔥",
    ties: "Empates",
    gastronomyBtn: "🍽️ Galería Gastronómica",
    saveScoreBtn: "Guardar",
    enterInitials: "¡Nuevo Récord! Iniciales:",
    musicJoropo: "Joropo (Clásico)",
    musicCountry: "Country (USA)",
    musicMix: "Fusión Norte-Sur",
    musicRetro: "Retro (Beeps)",
    lobbyTitle: "Sala Multijugador",
    hostBtn: "Crear Sala",
    joinBtn: "Unirse a Sala",
    roomCode: "Código de Sala:",
    enterCode: "Ingresa el Código:",
    waiting: "Esperando oponente...",
    copyBtn: "Copiar",
    connectBtn: "Conectar",
    cancelBtn: "Cancelar",
    mpDesc: "Juega con un amigo en otra computadora.",
    // Lobby Translations
    lobbyReady: "Listo",
    lobbySyncing: "Sincronizando...",
    lobbyLoading: "Cargando",
    lobbyHost: "Anfitrión",
    lobbyGuest: "Invitado",
    lobbyStart: "INICIAR JUEGO",
    lobbyWaitAssets: "Esperando carga de archivos...",
    lobbyAllReady: "¡Todos listos!",
    lobbyYouReady: "¡Estás Listo!",
    lobbyLoadingAssets: "Cargando archivos...",
    lobbyWaitHost: "Esperando al Host...",
    lobbyVerifying: "Verificando conexión...",
    rematchBtn: "Revancha",
    exitRoomBtn: "Salir de Sala",
    waitHostRestart: "Esperando reinicio...",
    triviaLabel: "💡 ¿Sabías que?",
    trivia: [
        "El chigüiro es el roedor más grande del mundo y ama el agua.",
        "El Joropo se baila zapateando duro, imitando el galope del caballo.",
        "La Mamona es carne de ternera asada en varas de madera.",
        "El Casanare es tierra de llaneros recios y atardeceres infinitos.",
        "Yopal significa 'Corazón' en lengua indígena.",
        "El coleo es el deporte principal del hombre llanero.",
        "La Virgen de Manare es la patrona de todos los casanareños."
    ]
};